version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: netflix-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mariadb:10.7
        container_name: netflix-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: netflix
            MYSQL_USER: netflix_user
            MYSQL_PASSWORD: netflix_password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
